language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  -  ls
  -  python kite/test_wavefunction.py

# Handle git submodules
git:
    submodules: false
# Replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive